"""Competition bootstrap — self-guided setup.

Verifies that the environment is clean (no competition-specific content in
wiki/skills), optionally extracts competition parameters from a rules
document, and generates a competition config.yaml.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def bootstrap_session(
    rules_doc_path: str | None = None,
    wiki_dir: str = "~/wiki",
    skills_dir: str = "~/.hermes/skills",
    output_config_path: str = "~/.competition/config.yaml",
) -> dict[str, Any]:
    """Self-guided competition setup.

    Steps:
    1. Run mask audit on wiki/ and skills/ for competition-specific content.
    2. Extract competition parameters from rules document (if provided).
       Currently supports basic keyword extraction from markdown files.
    3. Generate competition config.yaml with discovered parameters.
    4. Report clean/dirty status.

    Args:
        rules_doc_path: Optional path to competition rules document (PDF or markdown).
            Only plain-text/markdown extraction is supported currently.
        wiki_dir: Wiki directory to audit.
        skills_dir: Skills directory to audit.
        output_config_path: Path for generated config.yaml.

    Returns:
        Dict with keys: clean, violation_count, wiki_issues, skills_issues,
        extracted_params, config_path.
    """
    from .mask.rules import ALL_RULES
    from .mask.scanner import scan_directory

    wiki_path = Path(wiki_dir).expanduser()
    skills_path = Path(skills_dir).expanduser()

    # Step 1: Audit wiki
    wiki_results = scan_directory(wiki_path, ALL_RULES) if wiki_path.exists() else []
    wiki_issues = len(wiki_results)
    wiki_violations = sum(r["violation_count"] for r in wiki_results)

    # Step 2: Audit skills
    skills_results = (
        scan_directory(skills_path, ALL_RULES) if skills_path.exists() else []
    )
    skills_issues = len(skills_results)
    skills_violations = sum(r["violation_count"] for r in skills_results)

    total_violations = wiki_violations + skills_violations

    # Step 3: Extract params from rules doc (basic)
    extracted_params: dict[str, Any] = {}
    if rules_doc_path:
        doc_path = Path(rules_doc_path)
        if doc_path.exists():
            try:
                text = doc_path.read_text(encoding="utf-8")
                extracted_params = _basic_extract_params(text)
            except (OSError, UnicodeDecodeError):
                pass

    # Step 4: Generate config
    config_path = Path(output_config_path).expanduser()
    if total_violations > 0:
        # Don't generate config if environment isn't clean
        config_generated = False
        actual_config_path: str | None = None
    else:
        _generate_config(config_path, extracted_params)
        config_generated = True
        actual_config_path = str(config_path)

    return {
        "clean": total_violations == 0,
        "violation_count": total_violations,
        "wiki_issues": wiki_issues,
        "wiki_violations": wiki_violations,
        "skills_issues": skills_issues,
        "skills_violations": skills_violations,
        "extracted_params": extracted_params,
        "config_path": actual_config_path,
        "config_generated": config_generated,
    }


def _basic_extract_params(text: str) -> dict[str, Any]:
    """Extract competition parameters from rules document text.

    Uses simple keyword matching. This is a basic implementation —
    for production competition mode, this would use an LLM to parse
    the rules document structurally.
    """
    import re

    params: dict[str, Any] = {}

    # Span limit: look for patterns like "12 hour" or "maximum span"
    span_match = re.search(r"(\d+)\s*[- ]*hour", text, re.IGNORECASE)
    if span_match:
        params["max_span_hours"] = float(span_match.group(1))

    # Problem ID: look for "task1", "problem 1", etc.
    prob_match = re.search(r"(?:task|problem)\s*(\d+)", text, re.IGNORECASE)
    if prob_match:
        params["problem_id"] = f"task{prob_match.group(1)}"

    return params


def _generate_config(config_path: Path, params: dict[str, Any]) -> None:
    """Generate competition config.yaml from extracted parameters."""
    config_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Competition Mode Config",
        "# Auto-generated by expflow competition bootstrap",
        "# DO NOT commit this file to source control",
        "",
        "competition:",
        f"  problem_id: {params.get('problem_id', 'unknown')}",
        "  log:",
        f"    max_span_hours: {params.get('max_span_hours', 12.0)}",
        f"    max_elapsed_seconds: {params.get('max_elapsed_seconds', 60.0)}",
        "    allow_binary_check: true",
        "  bootstrap:",
        "    wiki_clean: true",
        "    skills_clean: true",
        "",
    ]

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
