"""Competition bootstrap — self-guided setup.

Verifies that the environment is clean (no competition-specific content in
wiki/skills), optionally extracts competition parameters from a rules
document, and generates a competition config.yaml.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def bootstrap_session(
    rules_doc_path: str | None = None,
    wiki_dir: str = "~/wiki",
    skills_dir: str = "~/.hermes/skills",
    output_config_path: str = "~/.competition/config.yaml",
) -> dict[str, Any]:
    """Self-guided competition setup.

    Steps:
    1. Run mask audit on wiki/ and skills/ for competition-specific content.
    2. Extract competition parameters from rules document (if provided).
       Currently supports basic keyword extraction from markdown files.
    3. Generate competition config.yaml with discovered parameters.
    4. Report clean/dirty status.

    Args:
        rules_doc_path: Optional path to competition rules document (PDF or markdown).
            Only plain-text/markdown extraction is supported currently.
        wiki_dir: Wiki directory to audit.
        skills_dir: Skills directory to audit.
        output_config_path: Path for generated config.yaml.

    Returns:
        Dict with keys: clean, violation_count, wiki_issues, skills_issues,
        extracted_params, config_path.
    """
    from .mask.rules import ALL_RULES
    from .mask.scanner import scan_directory

    wiki_path = Path(wiki_dir).expanduser()
    skills_path = Path(skills_dir).expanduser()

    # Step 1: Audit wiki
    wiki_results = scan_directory(wiki_path, ALL_RULES) if wiki_path.exists() else []
    wiki_issues = len(wiki_results)
    wiki_violations = sum(r["violation_count"] for r in wiki_results)

    # Step 2: Audit skills
    skills_results = (
        scan_directory(skills_path, ALL_RULES) if skills_path.exists() else []
    )
    skills_issues = len(skills_results)
    skills_violations = sum(r["violation_count"] for r in skills_results)

    total_violations = wiki_violations + skills_violations

    # Step 3: Extract params from rules doc (basic)
    extracted_params: dict[str, Any] = {}
    if rules_doc_path:
        doc_path = Path(rules_doc_path)
        if doc_path.exists():
            try:
                text = doc_path.read_text(encoding="utf-8")
                extracted_params = _basic_extract_params(text)
            except (OSError, UnicodeDecodeError):
                pass

    # Step 4: Generate config
    config_path = Path(output_config_path).expanduser()
    comp_dir = config_path.parent
    if total_violations > 0:
        # Don't generate config if environment isn't clean
        config_generated = False
        actual_config_path: str | None = None
    else:
        _generate_config(config_path, extracted_params)
        config_generated = True
        actual_config_path = str(config_path)

        # Step 4b: Generate scoring config template (to be filled by agent from rules)
        from .scoring import ProblemConfig

        pid = extracted_params.get("problem_id", "task1")
        scoring_cfg_path = comp_dir / f"scoring_{pid}.json"
        # Create an empty template — agent fills from rules document
        empty_cfg = ProblemConfig(problem_id=pid)
        _generate_scoring_template(scoring_cfg_path, empty_cfg)

    return {
        "clean": total_violations == 0,
        "violation_count": total_violations,
        "wiki_issues": wiki_issues,
        "wiki_violations": wiki_violations,
        "skills_issues": skills_issues,
        "skills_violations": skills_violations,
        "extracted_params": extracted_params,
        "config_path": actual_config_path,
        "config_generated": config_generated,
    }


def _basic_extract_params(text: str) -> dict[str, Any]:
    """Extract competition parameters from rules document text.

    Uses simple keyword matching. This is a basic implementation —
    for production competition mode, this would use an LLM to parse
    the rules document structurally.
    """
    import re

    params: dict[str, Any] = {}

    # Span limit: look for patterns like "12 hour" or "maximum span"
    span_match = re.search(r"(\d+)\s*[- ]*hour", text, re.IGNORECASE)
    if span_match:
        params["max_span_hours"] = float(span_match.group(1))

    # Problem ID: look for "task1", "problem 1", etc.
    prob_match = re.search(r"(?:task|problem)\s*(\d+)", text, re.IGNORECASE)
    if prob_match:
        params["problem_id"] = f"task{prob_match.group(1)}"

    return params


def _generate_config(config_path: Path, params: dict[str, Any]) -> None:
    """Generate competition config.yaml with multi-task support."""
    config_path.parent.mkdir(parents=True, exist_ok=True)

    problem_id = params.get('problem_id', 'task1')
    max_span = params.get('max_span_hours', 12.0)
    max_elapsed = params.get('max_elapsed_seconds', 60.0)

    lines = [
        "# Competition Mode Config",
        "# Auto-generated by expflow competition bootstrap",
        "# DO NOT commit this file to source control",
        "",
        "# To add more problems, add entries under competition.problems:",
        "#   competition:",
        "#     problems:",
        "#       task2:",
        "#         max_span_hours: 12",
        "#         max_elapsed_seconds: 60",
        "#         log_file: task2_logs.log",
        "#       task3:",
        "#         max_span_hours: 24",
        "#         max_elapsed_seconds: 90",
        "#         log_file: task3_logs.log",
        "",
        "competition:",
        f"  default_problem: {problem_id}",
        "  problems:",
        f"    {problem_id}:",
        f"      max_span_hours: {max_span}",
        f"      max_elapsed_seconds: {max_elapsed}",
        "      log_file: \"{{problem_id}}_logs.log\"",
        "      time_file: \"{{problem_id}}_time.csv\"",
        "      pred_file: \"{{problem_id}}_pred.hdf5\"",
        "  log:",
        f"    max_span_hours: {max_span}",
        f"    max_elapsed_seconds: {max_elapsed}",
        "    allow_binary_check: true",
        "  bootstrap:",
        "    wiki_clean: true",
        "    skills_clean: true",
        "",
    ]

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _generate_scoring_template(json_path: Path, cfg: "ProblemConfig") -> None:
    """Generate a scoring config JSON template (agent fills from rules document).

    The agent reads the competition rules document during bootstrap, extracts
    segment parameters, and fills them into this JSON. Then uses:
        expflow competition validate --score --score-config <this.json> ...
    """
    import json
    from pathlib import Path as _Path

    from .scoring import problem_config_to_dict

    path = _Path(json_path) if isinstance(json_path, str) else json_path
    data = problem_config_to_dict(cfg)
    data["_instructions"] = (
        "Fill the 'segments' array from the competition rules document. "
        "For each segment, set: label, start_step, end_step, weight, formula "
        "('exp_relmse' or 'max_lorentzian_frechet'), and coeff. "
        "Then run: expflow competition validate --score "
        "--gt <val_file.hdf5> --score-config this.json --submission <dir>"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
